schoolapp/urls.py
from django.urls import path
from .views import *

app_name = 'schoolapp'

urlpatterns = [
   path('',ClientHomeView.as_view(),name = 'clienthome'),
   path('contact/',ClientContactView.as_view() , name = 'clientcontact'),
   path('about/',ClientAboutView.as_view(),name = 'clientabout'),

]

schoolproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("schoolapp.urls")),

]
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

schoolapp/models.py
from django.db import models

# Create your models here.
class Slider(models.Model):
	title = models.CharField(max_length = 100)
	caption = models.CharField(max_length = 30)
	image = models.ImageField(upload_to = 'slider')
	link = models.CharField(max_length = 40)

	def __str__(self):
		return self.title

class Service(models.Model):
	title = models.CharField(max_length = 50)
	decription = models.TextField(max_length = 50)
	image = models.ImageField(upload_to = 'service')
	icon = models.CharField(max_length = 50)

	def __str__(self):
		return self.title

class Testimonial(models.Model):
	name = models.CharField(max_length = 20)
	image = models.ImageField(upload_to = 'testimonial')
	current_working = models.CharField(max_length = 50)
	saying = models.TextField(max_length = 100)

	def __str__(self):
		return self.name

class News(models.Model):
	title = models.CharField(max_length = 40)
	date = models.DateTimeField(auto_now_add = True)
	content = models.TextField(max_length = 100)
	image = models.ImageField(upload_to = 'news')

	def __str__(self):
		return self.title


class Category(models.Model):
	title = models.CharField(max_length = 30)
	icon = models.CharField(max_length = 13)
	image = models.ImageField(upload_to = 'course')

	def __str__(self):
		return self.title

class Course(models.Model):
	name = models.CharField(max_length = 50)
	category = models.ForeignKey(Category,on_delete = models.CASCADE , related_name = 'relatedcourse')
	content = models.TextField(max_length = 60)
	description = models.TextField(max_length = 50)
	icon = models.CharField(max_length = 50)
	image = models.ImageField(upload_to = 'course')
	duration = models.CharField(max_length = 50)

	def __str__(self):
		return self.name

class ContactForm(models.Model):
	name = models.CharField(max_length = 50)
	email = models.EmailField()
	mobile = models.CharField(max_length = 25)
	subject = models.CharField(max_length = 50)
	message = models.TextField(max_length = 30)

	def __str__(self):
		return self.name

schoolapp/forms.py
from .models import *
from django import forms

class MessageForm(forms.ModelForm):
	class Meta:
		model = ContactForm
		fields = "__all__"
		widgets = { 
			'name':forms.TextInput(attrs={'placeholder':"enter your name..."}),
			'mobile':forms.NumberInput(attrs = {'placeholder':"enter your mobile number"}),
			'email':forms.EmailInput(attrs = {'placeholder':"enter your email"}),
			'subject':forms.TextInput(attrs = {'placeholder':'enter your subject'}),
			'message':forms.TextInput(attrs = {'placeholder':"write the messages"}),

		 }

schoolapp/views.py
from django.shortcuts import render
from django.views.generic import *
from .models import *
from .forms import *


# Create your views here.

class ClientHomeView(TemplateView):
	template_name = 'clienttemplates/clienthome.html'

	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		context['sliders'] = Slider.objects.all()
		context['servicelist'] = Service.objects.all()
		context['alltestimonials'] = Testimonial.objects.all()
		context['allnews'] = News.objects.all()
		context['coursecategories'] = Category.objects.all()
		# context['courses'] = Course.objects.all()
		return context

class ClientContactView(CreateView):
	form_class = MessageForm
	template_name = 'clienttemplates/clientcontact.html'
	success_url = '/contact/'

class ClientAboutView(TemplateView):
	template_name = 'clienttemplates/clientabout.html'

templates/clienttemplates/base.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Instruction an Education Category Bootstrap Responsive Web Template | Home :: w3layouts</title>
	<!--/tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Instruction Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--//tags -->
	<link href="{% static 'clientstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'clientstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'clientstatic/css/owl.carousel.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'clientstatic/css/owl.theme.css' %}" type="text/css" media="all">
	<link href="{% static 'clientstatic/css/font-awesome.css' %}" rel="stylesheet">
	<!-- //for bootstrap working -->
	<link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">

		
</head>

<body>
	<!-- header -->
	<div class="header">
	<div class="agileits_top_menu">
		<div class="w3l_header_left">
				<ul>
					<li><i class="fa fa-phone" aria-hidden="true"></i> +456 123 7890</li>
					<li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com">info@example.com</a></li>
				</ul>
			</div>
			<div class="w3l_header_right">
				<div class="w3ls-social-icons text-left">
					<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
					<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
					<a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
					<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="content white agile-info">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
						<a class="navbar-brand" href="index.html">
							<h1><span class="fa fa-book" aria-hidden="true"></span> Instruction <label>Education</label></h1>
						</a>
					</div>
					<!--/.navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								<li class="active"><a href="{% url 'schoolapp:clienthome' %}" class="effect-3">Home</a></li>
								<li><a href="{% url 'schoolapp:clientabout' %}" class="effect-3">About</a></li>
								<li><a href="services.html" class="effect-3">Services</a></li>
								<li><a href="gallery.html" class="effect-3">Gallery</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">services<b class="caret"></b></a>
									<ul class="dropdown-menu">
										{% for service in servicelist %}
										<li><a href="codes.html">{{service.title}}</a></li>
										{% endfor %}
									</ul>
								</li>
								<li><a href="{% url 'schoolapp:clientcontact' %}" class="effect-3">Contact</a></li>
							</ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>
	</div>
{% block content %}
{% endblock %}
<!-- modal -->
	<!-- footer -->
	<div class="footer_top_agileits">
		<div class="container">
			<div class="col-md-4 footer_grid">
				<h3>About Us</h3>
				<p>Nam libero tempore cum vulputate id est id, pretium semper enim. Morbi viverra congue nisi vel pulvinar posuere sapien
					eros.
				</p>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Latest News</h3>
				<ul class="footer_grid_list">
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
					</li>
				</ul>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Contact Info</h3>
				<ul class="address">
					<li><i class="fa fa-map-marker" aria-hidden="true"></i>8088 USA, Honey block, <span>New York City.</span></li>
					<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="fa fa-phone" aria-hidden="true"></i>+09187 8088 9436</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="footer_grids">
				<div class="col-md-4 footer_grid_left">
					<h3>Sign up for our Newsletter</h3>
				</div>
				<div class="col-md-8 footer_grid_right">

					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter Email Address..." required="">
						<input type="submit" value="Submit">
					</form>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<div class="footer_w3ls">
		<div class="container">
					<div class="footer_bottom1">
						<p>© 2018 Instruction. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
					</div>
		</div>
	</div>
	<!-- //footer -->
	<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- js -->
	<script type="text/javascript" src="{% static 'clientstatic/js/jquery-2.1.4.min.js' %}"></script>

	<script type="text/javascript" src="{% static 'clientstatic/js/bootstrap.js' %}"></script>
	<!-- stats -->
	<script src="{% static 'clientstatic/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'clientstatic/js/jquery.countup.js' %}"></script>
	<script>
		$('.counter').countUp();
	</script>
	<!-- //stats -->
	<!-- owl carousel -->
	<script src="{% static 'clientstatic/js/owl.carousel.js' %}"></script>
	<script>
		$(document).ready(function () {
			$("#owl-demo").owlCarousel({

				autoPlay: 3000, //Set AutoPlay to 3 seconds
				autoPlay: true,
				items: 3,
				itemsDesktop: [991, 2],
				itemsDesktopSmall: [414, 4]

			});
		}); 
	</script>
	<!-- //owl carousel -->


</body>

</html>

templates/clienttemplates/clientabout.html
{% extends 'clienttemplates/base.html' %}
{% load static %}
{% block content %}	<!-- about -->
	<div class="welcome">
		<div class="container">
		<h3 class="heading-agileinfo">About me<span>When Climbing The Carrer Ladder</span></h3>
			<div class="w3ls_news_grids"> 
				<div class="col-md-6 w3_agile_about_grid_left">
					<h3>Pellentesque a ligula nec dui ornare pulvinar in non sem condimentum erat</h3>
					<p><i>In eleifend nisl fermentum bibendum euismod. Pellentesque ac mi quis tortor 
						consequat scelerisque.</i> Sed eros urna, rhoncus nec tortor quis, pretium vestibulum
						purus. Nunc quis augue nibh. Proin non enim non nulla scelerisque scelerisque 
						vitae non est. Quisque iaculis leo at lacus malesuada mattis.</p>
				</div>
				<div class="col-md-6 w3_agile_about_grid_right">
					<div class="skillbar" data-percent="78">
					  <span class="skillbar-title" style="background: #f1703a;">Lorem</span>
					  <p class="skillbar-bar" style="background: #f88c5e;"></p>
					  <span class="skill-bar-percent"></span>
					</div>
					<!-- End Skill Bar -->
					
					<div class="skillbar" data-percent="54">
					  <span class="skillbar-title" style="background: #2980b9;">Ipsum</span>
					  <p class="skillbar-bar" style="background: #3498db;"></p>
					  <span class="skill-bar-percent"></span>
					</div>
					<!-- End Skill Bar -->
					
					<div class="skillbar" data-percent="76">
					  <span class="skillbar-title" style="background: #a0d034;">Tortor</span>
					  <p class="skillbar-bar" style="background: #b2ec2f;"></p>
					  <span class="skill-bar-percent"></span>
					</div>
					<!-- End Skill Bar -->
					
					<div class="skillbar" data-percent="80">
					  <span class="skillbar-title" style="background: #e7cc2c;">Odio</span>
					  <p class="skillbar-bar" style="background: #f5d410;"></p>
					  <span class="skill-bar-percent"></span>
					</div>
					<!-- End Skill Bar -->
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //about -->

	<div class="about-w3slid jarallax">
		<div class="subscribe-agileinfo"> 
			<div class="container">  
				<h3>Lorem ipsum dolor sit amet</h3>
				<p>Curabitur nec purus eget urna pulvinar placerat. Integer varius est vitae iaculis suscipit. Nam libero tempore cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus omnis optio </p> 
			</div>
		</div>
	</div>
<!-- team -->
	<div class="team">
		<div class="container">
		<h3 class="heading-agileinfo">Meet Our Staff<span>When Climbing The Carrer Ladder</span></h3>
			<div class="w3_agile_team_grids">
				<div class="col-md-3 w3_agile_team_grid">
					<div class="hover14 column">
						<figure><img src="images/t1.jpg" alt=" " class="img-responsive" /></figure>
					</div>
					<h3>Amanda Seylon</h3>
					<p>Lorem</p>
					<ul class="agileits_social_list">
						<li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<div class="col-md-3 w3_agile_team_grid">
					<div class="hover14 column">
						<figure><img src="images/t2.jpg" alt=" " class="img-responsive" /></figure>
					</div>
					<h3>Laura Mark</h3>
					<p>Donec</p>
					<ul class="agileits_social_list">
						<li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<div class="col-md-3 w3_agile_team_grid">
					<div class="hover14 column">
						<figure><img src="images/t3.jpg" alt=" " class="img-responsive" /></figure>
					</div>
					<h3>Lusiana James</h3>
					<p>Vivamus</p>
					<ul class="agileits_social_list">
						<li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<div class="col-md-3 w3_agile_team_grid">
					<div class="hover14 column">
						<figure><img src="images/t4.jpg" alt=" " class="img-responsive" /></figure>
					</div>
					<h3>Catharine</h3>
					<p>Sagittis</p>
					<ul class="agileits_social_list">
						<li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- team -->


{% endblock %}

templates/clienttemplates/clientcontact.html
{% extends 'clienttemplates/base.html' %}
{% load static %}
{% block content %}
<div class="inner_content_info_agileits">
		<div class="container">
			<h3 class="heading-agileinfo">Contact Us<span>When Climbing The Carrer Ladder</span></h3>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-4 agile_info_mail_img_info">
					<div class="address-grid">
						<h4>Contact <span>Info</span></h4>
						<div class="mail-agileits-w3layouts">
							<i class="fa fa-volume-control-phone" aria-hidden="true"></i>
							<div class="contact-right">
								<p>Telephone </p><span>+1 (100)222-23-33</span>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="mail-agileits-w3layouts">
							<i class="fa fa-envelope-o" aria-hidden="true"></i>
							<div class="contact-right">
								<p>Mail </p><a href="mailto:info@example.com">info@example.com</a>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="mail-agileits-w3layouts">
							<i class="fa fa-map-marker" aria-hidden="true"></i>
							<div class="contact-right">
								<p>Location</p><span>8088 USA, Honey block,New York City.</span>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="agileits_w3layouts_nav_right contact">
							<div class="social two">
								<ul>
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-rss"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-8 agile_info_mail_img">

				</div>
				<div class="clearfix"> </div>
				<div class="w3layouts_mail_grid">
					<form method="post">
						{% csrf_token %}
						<div class="col-md-6 wthree_contact_left_grid">
							{{ form.name }}
							{{ form.email }}
							{{ form.mobile }}
							{{ form.subject }}

<!-- 							<input type="text" name="Name" placeholder="Name" required="">
							<input type="email" name="Email" placeholder="Email" required="">
							<input type="text" name="Telephone" placeholder="Telephone" required="">
							<input type="text" name="Subject" placeholder="Subject" required=""> -->
						</div>
						<div class="col-md-6 wthree_contact_left_grid">
							{{ form.message }}
							<!-- <textarea name="Message" placeholder="Message..." required=""></textarea> -->
							<input type="submit" value="Submit">
						</div>
						<div class="clearfix"> </div>

					</form>
				</div>


			</div>

		</div>
	</div>
	<!-- //mid-services -->
	<!-- /map -->
	<div class="map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387142.84010033106!2d-74.25819252532891!3d40.70583163828471!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew+York%2C+NY%2C+USA!5e0!3m2!1sen!2sin!4v1475140387172"
		    style="border:0"></iframe>

	</div>


{% endblock %}